weight:
    pattern:  /
    defaults: { _controller: "SFCapBundle:UserWeight:index" }

weight_show:
    pattern:  /{id}/show
    defaults: { _controller: "SFCapBundle:UserWeight:show" }

weight_new:
    pattern:  /new
    defaults: { _controller: "SFCapBundle:UserWeight:new" }

weight_create:
    pattern:  /create
    defaults: { _controller: "SFCapBundle:UserWeight:create" }
    requirements: { _method: post }

weight_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "SFCapBundle:UserWeight:edit" }

weight_update:
    pattern:  /{id}/update
    defaults: { _controller: "SFCapBundle:UserWeight:update" }
    requirements: { _method: post }

weight_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "SFCapBundle:UserWeight:delete" }
    requirements: { _method: post }